### PR TITLE
1. Translated pdf instructions to Spanish. 2. Added clarification to …

### PR DESCRIPTION
**Pull request by paulo-g-martinez**
…write initials inside parenthesis. 3. added periods to instructions. 4. subbed parents to parent(s)/legal guardian(s) in English instructions. 5. subbed (initial) for (write their initials) in English instructions. 6. added instructions to print two copies.

### CODE REVIEW

**Comment by CoreyAR** [comment]
Awesome! Thanks @paulo-g-martinez !

**Comment by CoreyAR** [comment]
Looks like it failed linting. The errors look like the can be fixed with `yarn run lint:fix`.

You can see the errors by looking at the details for the travis ci build above.

Once it passes, it can be merged.

**Comment by ntbrewer** [comment]
I might also recommend that "el / Los"  on items 3&4 are changed to "el/los" (remove capital).

**Comment by paulo-g-martinez** [comment]
Right. Sorry about that. I hadn't ever worked with yarn or js before but I think I got it figured out. Let's see if this one works. It's working locally. 
- decapitalized "el/Los" to "el/los"
- ran: `yarn run lint:fix` 
- (btw I had to "downgrade" my node. I think the default `brew install yarn` set me up with version 10.something.)

**Pull request merged**
